server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /healthz {
    add_header Content-Type text/plain;
    return 200 'ok\n';
  }

  location = /oferta-lua-1 { rewrite ^ /sales.html?variant=br-v1 last; }
  location = /oferta-lua-2 { rewrite ^ /sales.html?variant=br-v2 last; }
  location = /es/oferta-lua-1 { rewrite ^ /sales.html?variant=es-v1 last; }
  location = /es/oferta-lua-2 { rewrite ^ /sales.html?variant=es-v2 last; }
  location ~ ^/oferta-lua-1/?$ { rewrite ^ /sales.html?variant=br-v1 last; }
  location ~ ^/oferta-lua-2/?$ { rewrite ^ /sales.html?variant=br-v2 last; }
  location ~ ^/es/oferta-lua-1/?$ { rewrite ^ /sales.html?variant=es-v1 last; }
  location ~ ^/es/oferta-lua-2/?$ { rewrite ^ /sales.html?variant=es-v2 last; }

  location /api/ {
    proxy_pass http://api:8000;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location ~* \.(?:html|js)$ {
    add_header Cache-Control "no-cache" always;
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
